//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", ConfigurationName="ESIS.IESIS_TecItrLearnerEventServices_v1")]
    public interface IESIS_TecItrLearnerEventServices_v1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:nzl:govt:educating:integration:tec:itr:1/UploadLearnerEventData", ReplyAction="http://Microsoft.WCF.Documentation/ResponseToOCAMethod")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ESIS.UploadLearnerEventDataResponse> UploadLearnerEventDataAsync(ESIS.UploadLearnerEventDataRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:nzl:govt:educating:integration:tec:itr:1/GetLearnerEventResults", ReplyAction="urn:nzl:govt:educating:integration:tec:itr:1/GetLearnerEventResultsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ESIS.GetLearnerEventResultsResponse> GetLearnerEventResultsAsync(ESIS.GetLearnerEventResultsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:nzl:govt:educating:integration:tec:itr:1/FetchLearnerEventData", ReplyAction="urn:nzl:govt:educating:integration:tec:itr:1/FetchLearnerEventDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ESIS.FetchLearnerEventDataResponse> FetchLearnerEventDataAsync(ESIS.FetchLearnerEventDataRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:nzl:govt:educating:integration:tec:itr:1/FetchLearnerEventDataResults", ReplyAction="urn:nzl:govt:educating:integration:tec:itr:1/FetchLearnerEventDataResultsResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ESIS.FetchLearnerEventDataResultsResponse> FetchLearnerEventDataResultsAsync(ESIS.FetchLearnerEventDataResultsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1")]
    public partial class MessageHeadersType
    {
        
        private string esaaUsernameField;
        
        private string esaaPasswordField;
        
        private string providerNumberField;
        
        private string tMSUsernameField;
        
        private System.DateTime messageSentTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EsaaUsername
        {
            get
            {
                return this.esaaUsernameField;
            }
            set
            {
                this.esaaUsernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EsaaPassword
        {
            get
            {
                return this.esaaPasswordField;
            }
            set
            {
                this.esaaPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProviderNumber
        {
            get
            {
                return this.providerNumberField;
            }
            set
            {
                this.providerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TMSUsername
        {
            get
            {
                return this.tMSUsernameField;
            }
            set
            {
                this.tMSUsernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime MessageSentTime
        {
            get
            {
                return this.messageSentTimeField;
            }
            set
            {
                this.messageSentTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1")]
    public partial class FetchLearnerEventDataResultType
    {
        
        private string messageIdField;
        
        private MessageStatusCodeType statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private System.Xml.XmlElement learnerEventDataResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MessageStatusCodeType StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusCodeSpecified
        {
            get
            {
                return this.statusCodeFieldSpecified;
            }
            set
            {
                this.statusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Xml.XmlElement LearnerEventDataResult
        {
            get
            {
                return this.learnerEventDataResultField;
            }
            set
            {
                this.learnerEventDataResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1")]
    public enum MessageStatusCodeType
    {
        
        /// <remarks/>
        RECEIVED,
        
        /// <remarks/>
        DELIVERED,
        
        /// <remarks/>
        PROCESSED,
        
        /// <remarks/>
        RETRIEVED,
        
        /// <remarks/>
        MESSAGE_ERROR,
        
        /// <remarks/>
        UNKOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1")]
    public partial class FetchEventDataMessageType
    {
        
        private string schemaVersionField;
        
        private System.Xml.XmlElement fetchTertiaryPerformanceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SchemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Xml.XmlElement FetchTertiaryPerformanceData
        {
            get
            {
                return this.fetchTertiaryPerformanceDataField;
            }
            set
            {
                this.fetchTertiaryPerformanceDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1")]
    public partial class ServicePollingPolicyType
    {
        
        private SLAStatusType sLAStatusField;
        
        private int callBackInSecondsField;
        
        private bool callBackInSecondsFieldSpecified;
        
        private string sLAMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SLAStatusType SLAStatus
        {
            get
            {
                return this.sLAStatusField;
            }
            set
            {
                this.sLAStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CallBackInSeconds
        {
            get
            {
                return this.callBackInSecondsField;
            }
            set
            {
                this.callBackInSecondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CallBackInSecondsSpecified
        {
            get
            {
                return this.callBackInSecondsFieldSpecified;
            }
            set
            {
                this.callBackInSecondsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SLAMessage
        {
            get
            {
                return this.sLAMessageField;
            }
            set
            {
                this.sLAMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1")]
    public enum SLAStatusType
    {
        
        /// <remarks/>
        SLA_MEET,
        
        /// <remarks/>
        SLA_FAILURE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1")]
    public partial class LearnerEventResultType
    {
        
        private string messageIdField;
        
        private MessageStatusCodeType statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private System.Xml.XmlElement iTRResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MessageStatusCodeType StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusCodeSpecified
        {
            get
            {
                return this.statusCodeFieldSpecified;
            }
            set
            {
                this.statusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Xml.XmlElement ITRResult
        {
            get
            {
                return this.iTRResultField;
            }
            set
            {
                this.iTRResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1")]
    public partial class MessageIdListType
    {
        
        private string schemaVersionField;
        
        private string[] messageIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SchemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MessageId", Order=1)]
        public string[] MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1")]
    public partial class EventDataMessageType
    {
        
        private string schemaVersionField;
        
        private System.Xml.XmlElement tertiaryPerformanceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SchemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Xml.XmlElement TertiaryPerformanceData
        {
            get
            {
                return this.tertiaryPerformanceDataField;
            }
            set
            {
                this.tertiaryPerformanceDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadLearnerEventDataRequest", WrapperNamespace="urn:nzl:govt:educating:integration:tec:itr:1", IsWrapped=true)]
    public partial class UploadLearnerEventDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=0)]
        public ESIS.MessageHeadersType MessageHeaders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=1)]
        public ESIS.EventDataMessageType PerformanceDataMessage;
        
        public UploadLearnerEventDataRequest()
        {
        }
        
        public UploadLearnerEventDataRequest(ESIS.MessageHeadersType MessageHeaders, ESIS.EventDataMessageType PerformanceDataMessage)
        {
            this.MessageHeaders = MessageHeaders;
            this.PerformanceDataMessage = PerformanceDataMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadLearnerEventDataResponse", WrapperNamespace="urn:nzl:govt:educating:integration:tec:itr:1", IsWrapped=true)]
    public partial class UploadLearnerEventDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=0)]
        public string MessageId;
        
        public UploadLearnerEventDataResponse()
        {
        }
        
        public UploadLearnerEventDataResponse(string MessageId)
        {
            this.MessageId = MessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLearnerEventResultsRequest", WrapperNamespace="urn:nzl:govt:educating:integration:tec:itr:1", IsWrapped=true)]
    public partial class GetLearnerEventResultsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=0)]
        public ESIS.MessageHeadersType MessageHeaders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=1)]
        public ESIS.MessageIdListType MessageIdList;
        
        public GetLearnerEventResultsRequest()
        {
        }
        
        public GetLearnerEventResultsRequest(ESIS.MessageHeadersType MessageHeaders, ESIS.MessageIdListType MessageIdList)
        {
            this.MessageHeaders = MessageHeaders;
            this.MessageIdList = MessageIdList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLearnerEventResultsResponse", WrapperNamespace="urn:nzl:govt:educating:integration:tec:itr:1", IsWrapped=true)]
    public partial class GetLearnerEventResultsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LearnerEventResult", IsNullable=false)]
        public ESIS.LearnerEventResultType[] LearnerEventResultList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=1)]
        public ESIS.ServicePollingPolicyType ServicePollingPolicy;
        
        public GetLearnerEventResultsResponse()
        {
        }
        
        public GetLearnerEventResultsResponse(ESIS.LearnerEventResultType[] LearnerEventResultList, ESIS.ServicePollingPolicyType ServicePollingPolicy)
        {
            this.LearnerEventResultList = LearnerEventResultList;
            this.ServicePollingPolicy = ServicePollingPolicy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FetchLearnerEventDataRequest", WrapperNamespace="urn:nzl:govt:educating:integration:tec:itr:1", IsWrapped=true)]
    public partial class FetchLearnerEventDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=0)]
        public ESIS.MessageHeadersType MessageHeaders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=1)]
        public ESIS.FetchEventDataMessageType FetchPerformanceDataMessage;
        
        public FetchLearnerEventDataRequest()
        {
        }
        
        public FetchLearnerEventDataRequest(ESIS.MessageHeadersType MessageHeaders, ESIS.FetchEventDataMessageType FetchPerformanceDataMessage)
        {
            this.MessageHeaders = MessageHeaders;
            this.FetchPerformanceDataMessage = FetchPerformanceDataMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FetchLearnerEventDataResponse", WrapperNamespace="urn:nzl:govt:educating:integration:tec:itr:1", IsWrapped=true)]
    public partial class FetchLearnerEventDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=0)]
        public string MessageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=1)]
        public ESIS.ServicePollingPolicyType ServicePolicy;
        
        public FetchLearnerEventDataResponse()
        {
        }
        
        public FetchLearnerEventDataResponse(string MessageId, ESIS.ServicePollingPolicyType ServicePolicy)
        {
            this.MessageId = MessageId;
            this.ServicePolicy = ServicePolicy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FetchLearnerEventDataResultsRequest", WrapperNamespace="urn:nzl:govt:educating:integration:tec:itr:1", IsWrapped=true)]
    public partial class FetchLearnerEventDataResultsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=0)]
        public ESIS.MessageHeadersType MessageHeaders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=1)]
        public string SchemaVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=2)]
        public string MessageId;
        
        public FetchLearnerEventDataResultsRequest()
        {
        }
        
        public FetchLearnerEventDataResultsRequest(ESIS.MessageHeadersType MessageHeaders, string SchemaVersion, string MessageId)
        {
            this.MessageHeaders = MessageHeaders;
            this.SchemaVersion = SchemaVersion;
            this.MessageId = MessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FetchLearnerEventDataResultsResponse", WrapperNamespace="urn:nzl:govt:educating:integration:tec:itr:1", IsWrapped=true)]
    public partial class FetchLearnerEventDataResultsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=0)]
        public ESIS.FetchLearnerEventDataResultType FetchLearnerEventDataResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:nzl:govt:educating:integration:tec:itr:1", Order=1)]
        public ESIS.ServicePollingPolicyType ServicePolicy;
        
        public FetchLearnerEventDataResultsResponse()
        {
        }
        
        public FetchLearnerEventDataResultsResponse(ESIS.FetchLearnerEventDataResultType FetchLearnerEventDataResult, ESIS.ServicePollingPolicyType ServicePolicy)
        {
            this.FetchLearnerEventDataResult = FetchLearnerEventDataResult;
            this.ServicePolicy = ServicePolicy;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IESIS_TecItrLearnerEventServices_v1Channel : ESIS.IESIS_TecItrLearnerEventServices_v1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ESIS_TecItrLearnerEventServices_v1Client : System.ServiceModel.ClientBase<ESIS.IESIS_TecItrLearnerEventServices_v1>, ESIS.IESIS_TecItrLearnerEventServices_v1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ESIS_TecItrLearnerEventServices_v1Client() : 
                base(ESIS_TecItrLearnerEventServices_v1Client.GetDefaultBinding(), ESIS_TecItrLearnerEventServices_v1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IESIS_TecItrLearnerEventServices_v1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ESIS_TecItrLearnerEventServices_v1Client(EndpointConfiguration endpointConfiguration) : 
                base(ESIS_TecItrLearnerEventServices_v1Client.GetBindingForEndpoint(endpointConfiguration), ESIS_TecItrLearnerEventServices_v1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ESIS_TecItrLearnerEventServices_v1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ESIS_TecItrLearnerEventServices_v1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ESIS_TecItrLearnerEventServices_v1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ESIS_TecItrLearnerEventServices_v1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ESIS_TecItrLearnerEventServices_v1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESIS.UploadLearnerEventDataResponse> ESIS.IESIS_TecItrLearnerEventServices_v1.UploadLearnerEventDataAsync(ESIS.UploadLearnerEventDataRequest request)
        {
            return base.Channel.UploadLearnerEventDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESIS.UploadLearnerEventDataResponse> UploadLearnerEventDataAsync(ESIS.MessageHeadersType MessageHeaders, ESIS.EventDataMessageType PerformanceDataMessage)
        {
            ESIS.UploadLearnerEventDataRequest inValue = new ESIS.UploadLearnerEventDataRequest();
            inValue.MessageHeaders = MessageHeaders;
            inValue.PerformanceDataMessage = PerformanceDataMessage;
            return ((ESIS.IESIS_TecItrLearnerEventServices_v1)(this)).UploadLearnerEventDataAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ESIS.GetLearnerEventResultsResponse> GetLearnerEventResultsAsync(ESIS.GetLearnerEventResultsRequest request)
        {
            return base.Channel.GetLearnerEventResultsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESIS.FetchLearnerEventDataResponse> FetchLearnerEventDataAsync(ESIS.FetchLearnerEventDataRequest request)
        {
            return base.Channel.FetchLearnerEventDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESIS.FetchLearnerEventDataResultsResponse> FetchLearnerEventDataResultsAsync(ESIS.FetchLearnerEventDataResultsRequest request)
        {
            return base.Channel.FetchLearnerEventDataResultsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IESIS_TecItrLearnerEventServices_v1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IESIS_TecItrLearnerEventServices_v1))
            {
                return new System.ServiceModel.EndpointAddress("http://itrmq-uat.tec.govt.nz/ESIS_TecItrLearnerEventServices_v1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ESIS_TecItrLearnerEventServices_v1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IESIS_TecItrLearnerEventServices_v1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ESIS_TecItrLearnerEventServices_v1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IESIS_TecItrLearnerEventServices_v1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IESIS_TecItrLearnerEventServices_v1,
        }
    }
}
